### ISSUE TITLE
Footer Widgets

### ISSUE THREAD

**Issue by badcat** [plutonwp/pluton#1]
Hello - great theme!

There's something going on with the Footer and Widgets using the default v 1.0.6 theme.

I see the following error:

```Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'php_execute' not found or invalid function name in ../public_html/sitename/wp-includes/plugin.php on line 235```

I'm not able to pinpoint the issue for you but seems to happen when adding widgets.

**Comment by plutonwp** [comment]
Hello,

Thank you very much for your message and for reporting this issue :)
I've updated the theme, it should not have this problem anymore, tell me if it work.

Best regards

**Comment by badcat** [comment]
Hello,
Yes - this fix fixes the sidebar footer file.
thank you!

**Comment by plutonwp** [comment]
You're welcome :)
