### ISSUE TITLE
Template hierarchy: Blog template

### ISSUE THREAD

**Issue by justintadlock** [plutonwp/pluton#14]
The `templates/blog.php` template is unnecessary and does not work if the user has correctly set up their posts page.  `home.php` is the correct template to use for the home/posts page in WordPress.  So, just rename that file to `home.php` and move it up to the root folder.

You don't need a custom query either.  You can use the normal WP posts loop.

**Comment by plutonwp** [comment]
It is not for the home page, is to display the blog in any page, if a user wants to use a page to view its posts, how he does without template page?

**Comment by justintadlock** [comment]
The user only needs to go to Settings > Reading > Front Page Displays in the WP admin.  Then, they can select a custom front page and set the "posts page" to a page of their choosing.

**Comment by plutonwp** [comment]
Okay, I'll just delete the template for blog because the home page there is the index file that displays the latest posts if no home page is defined.
Thank you :)
