### ISSUE TITLE
Plugin territory: SSL for attachments

### ISSUE THREAD

**Issue by justintadlock** [plutonwp/pluton#15]
The `honor_ssl_for_attachments()` filter in `functions.php` is plugin territory and should be removed.  It's probably a good bit of code, but it doesn't belong in a theme.  Leave SSL to plugins.

**Comment by badcat** [comment]
Yikes! Justin's in the house  :)  Go man go!  Actually this feels like  a pretty good sign to have Justin even taking a look, no?
