### ISSUE TITLE
Styling: Gallery

### ISSUE THREAD

**Issue by justintadlock** [plutonwp/pluton#19]
The `[gallery]` shortcode output could use some work.  Right now, all the images just line up to the left of the post content area.  I'd recommend utilizing the entire post content container.  See screenshot.

![gallery](https://cloud.githubusercontent.com/assets/1816309/16921036/814faa2a-4cd5-11e6-8bc8-d77131854345.png)

**Comment by plutonwp** [comment]
It's weird, I did not have this problem, look:
![capture](https://cloud.githubusercontent.com/assets/19571921/16991024/7ae4e01c-4e9a-11e6-82d9-ae60beb8ac37.PNG)

**Comment by justintadlock** [comment]
Try a smaller image size.
