### ISSUE TITLE
Top Bar Social Links

### ISSUE THREAD

**Issue by badcat** [plutonwp/pluton#2]
Hello.
This is probably a Feature Request and not a bug -- Top Bar social links are not the same as the ones in the Footer Widget Social Icons -- They have a different order, missing FourSquare etc.  Perhaps these should match each other?
thank you.

**Comment by plutonwp** [comment]
Hello, look at the documentation: http://docs.plutonwp.com/article/136-alter-the-top-bar-social-icons
You can add or reorder the social of the top bar :)

**Comment by badcat** [comment]
Great - thank you.  Yes, I need to study your docs more. :)

**Comment by plutonwp** [comment]
Everything is explained so you can do the customizations you want :)
