### ISSUE TITLE
WordPress.org requirements

### ISSUE THREAD

**Issue by justintadlock** [plutonwp/pluton#28]
I know you were releasing this as a free theme, but I wasn't sure if you planned to submit to .ORG.  If so, I'm just opening this ticket to keep a running list of things you need to get rid of **only if submitting to WordPress.org**.  Feel free to close if not planning to submit there.

* Theme updater.
* Appearance > Image Size screen.
* Appearance > Customizer Manager screen.

**Comment by plutonwp** [comment]
Yes, I submitted the theme on wp.org, for "Theme updater" it's in pending the review, then I would delete it.
