### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by sakinshrestha** [plutonwp/pluton#33]
* In `functions.php` line 617, there is a check with setting `minify_js_enable`, however, this setting is not present anywhere on theme, so this always returns true
* Hence this code check becomes irrelevant

**Comment by plutonwp** [comment]
This is an option I've integrate in an external plugin that I recommend to install, I have the right to do that, right?

**Comment by sakinshrestha** [comment]
Yes, if that is used then it's fine.

**Comment by plutonwp** [comment]
Great, thank you :)
