### ISSUE TITLE
Theme Panel Menu Item shows for all Roles

### ISSUE THREAD

**Issue by badcat** [plutonwp/pluton#39]
Perhaps the "Theme Panel" top level menu item should be hidden for user roles less than Author?  I can imagine why a subscriber would need to access the Pluton docs.  Here's what it looks like to a Subscriber.
![panel](https://cloud.githubusercontent.com/assets/26096/17703810/05911328-63a1-11e6-9f06-5bd55d377d00.png)

**Comment by plutonwp** [comment]
You are absolutely right, problem solved for the next update :)
Thank you a lot.
