### ISSUE TITLE
Purpose of $pluton_theme_mods

### ISSUE THREAD

**Issue by justintadlock** [plutonwp/pluton#4]
What is the purpose of `$pluton_theme_mods` and its related functions?  I don't see any additional features that are extending what core WP already does.  I often see this sort of thing when theme authors are thinking this is faster because it avoids database lookups.  If that's the purpose, this won't help.  WordPress loads theme mods and caches the results on every page load, so this won't speed anything up.

The `pluton_get_mod()` function actually breaks existing core functionality because it bypasses the `theme_mod_{$mod}` hook.  This is actually a quite useful hook for child theme development.

My recommendation would be to simply use the core theme mod functionality.

**Comment by plutonwp** [comment]
So if I use "get_theme_mod" instead of "pluton_get_mod" it is the same?

**Comment by justintadlock** [comment]
Yes, you get the same result.  

However, they are not exactly the same because `pluton_get_mod()` breaks filters.

**Comment by plutonwp** [comment]
Okay, so it's better to use "get_theme_mod".

**Comment by justintadlock** [comment]
Yes.

**Comment by plutonwp** [comment]
Thank you :)
