### ISSUE TITLE
Top Bar menu and Top Bar content shift

### ISSUE THREAD

**Issue by badcat** [plutonwp/pluton#40]
Upon page load I find the content and menu shift when using both, the Top Bar menu and Top Bar Content.  The Top Bar Content breaks into 2 lines. Replicating the content ONLY via the Menu system eliminates the breaking/shifting issue.  I'm using Left Content and Right Social

**Comment by plutonwp** [comment]
Hello, sorry, I misunderstood your problem, can you send me a screenshot or send me the URL of the page where you have this issue?
Thank you.

**Comment by badcat** [comment]
hello!  Sure - the issue is the Top Bar content moves to the 2nd line - after the Top Bar menu items
![screen shot 2016-08-22 at 7 14 53 pm](https://cloud.githubusercontent.com/assets/26096/17874966/ebc329c6-689c-11e6-93a7-04de8636ca8f.png)

**Comment by plutonwp** [comment]
Ok now I understand :)
I think this is a small problem, to be sure, can you send me the URL of the site where you have this problem if you do not want to spread your url on github, you can send it to me directly to plutontheme[at]gmail[dot]com.

**Comment by badcat** [comment]
emailed you - thanks.

**Comment by plutonwp** [comment]
I replied to you :)

**Comment by badcat** [comment]
Yes - it's rock solid in Chrome and Firefox of course :)  It's Safari Version 9.1.2 under OSX 10.11.6 as usual. :(  I noticed it while using Safari's "Responsive Design Mode" to emulate iPad Pro (iOS 9.3) as I didn't have that specific device.  But it also intermittently breaks in regular "desktop" view too. No big deal I suppose.

**Comment by plutonwp** [comment]
You can try to wrap with a div your top bar content like this:

<div style="display: block; float: left;">YOUR CONTENT</div>

Replace "YOUR CONTENT" with your content.

Tell me if this solves the problem.

**Comment by badcat** [comment]
Yes - that solves this problem, but creates another for the mobile media query since it's no longer centering the content on smaller devices.  But good to know where to start  :)   thank you.

**Comment by badcat** [comment]
Smart 👍 Solved!

**Comment by plutonwp** [comment]
Great :)
If you have another problem, do not hesitate to contact me :)
